python:
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet18" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet18" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet34" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet34" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet50" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet50" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet101" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet101" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet152" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "resnet152" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet121" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet121" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet161" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet161" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet169" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet169" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet201" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "densenet201" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "squeezenet1_0" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "squeezenet1_0" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "squeezenet1_1" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "squeezenet1_1" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "inception_v3" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "inception_v3" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg11" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg11" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg13" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg13" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg16" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg16" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg19" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg19" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg11_bn" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg11_bn" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg13_bn" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg13_bn" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg16_bn" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg16_bn" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg19_bn" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "vgg19_bn" -f "False" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "alexnet" -f "True" -ep 200
	python model1.py -idl "data/training_data" -sl "models/" -g "True" -mo "alexnet" -f "False" -ep 200
